server:
  port: 50200
spring:
  # 解决中文乱码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: govern-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/tanxingsong/micro-service-config.git
          # 根据项目名去寻找对应文件夹下的配置文件
          searchPaths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: govern-config